config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
        namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
# アソシエーションを設定する。
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users #多対多記述。has_many引数に「アソシ組みたいテーブル名」を、:throughのバリューに「中間テーブル名」を指定。これで「group.users」といった呼出ができる。
  has_many :messages
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
# アソシエーション設定
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # アソシエーション設定
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #?
  
  validates :name, presence: true, uniqueness: true    #?
  
  has_many :group_users
  has_many :groups, through: :group_users #?
  has_many :messages
  
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id]
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
# コマンドrails g controller groupsで作成されたファイル
class GroupsController < ApplicationController

  def index
  end

  def new #新規登録に必要なアクション
    @group = Group.new #newアクション中で@gに空インスタ代入。form_withで使用する変数。
    @group.users << current_user #「<<」配列に要素を追加する。CS仕様でg新規作成時必ずログインユーザーを含めたいので予め追加。
  end

  def create #新規登録に必要なアクション→ルーティング設定 resources :groups, only: [:new, :create] を設定
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end #保存の状態で分岐。OKならif。違ったらelseで新規登録画面。redirectはリクエスト送信と同じでC→V。renはそのままV。これにより元のインスタンス変数の値が上書きされるかどうかが違ってくる。今回はgが保存されなかったらフォームに入力内容を保持してグループ作成画面を表示。
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: []) #ストロングパラメーター。配列に対し保存を許可したい場合キーの名称と関連づけてバリューに「[]」と記述。
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

#  問題 9. グループ編集後のリダイレクト先を変更しよう
  def update
    if current_user.update(user_params)
      redirect_to root_path
      # redirect_to group_messages_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_with model: group, local: true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "グループ名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'グループ名を入力してください'
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField
      .UserSearch
        %input#UserSearch__field.SettingGroupForm__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #UserSearchResult
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, value: "チャットメンバー", class: "SettingGroupForm__label"
    .SettingGroupForm__rightField
      .ChatMembers
        .ChatMember
          %p.ChatMember__name= current_user.name
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
        - group.users.each do |user|
          - if current_user.name != user.name
            .ChatMember
              %p.ChatMember__name 
                = user.name
              .ChatMember__remove.ChatMember__button{"data-user-id": user.id, "data-user-name": user.name} 削除
              %input{name: "group[user_ids][]", type:"hidden", value: user.id}
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'

app/views/groups/edit.html.haml
.SettingGroupForm
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }



-# = form_with model: @group, local: true do |f|
-#   = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
-#   = f.collection_check_boxes :user_ids, User.all, :id, :name

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

  -# side_bar.html.hamlを呼び出す

app/views/groups/new.html.haml
.SettingGroupForm
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }




-# -# form_withの使い方を把握すること
-# = form_with model: @group, local: true do |f|
-#   = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
-#   = f.collection_check_boxes :user_ids, User.all, :id, :name #ビューにチェックボックスの表示を行うためのヘルパーメソッド。第１引数は送信されるハッシュの「キー」。第２で表示されるためのデータを指定。第３は送信されるハッシュの「バリュー」。第４で上記データのどのカラムを表示させるかを指定。
-#   = f.submit "Save", class: "SettingGroupForm__button"

app/views/layouts/_notifications.html.haml
-# フラッシュメッセージを表示するためのビュー
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
-# どのビューを表示する時も必ず表示されるようデフォルト設定されているファイル。
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    -# = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    -# 10行目は削除する
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
-# 問題7. ヘッダーにグループ名とユーザー名が表示されるようにしよう
-# 問題8. グループ編集ページへのリンクを設置しよう
.chat
  .chat__c-header
    .chat__c-header__group
      %h1.g-name 
        = @group.name
      %p.u-name
        - @group.users.each do |user|
          = user.name
    .chat__c-header__edit
      = link_to 'edit',class: "button" do
        Edit

  .chat__main
    = render @messages 
    
  -# .chat__main
  -#   .chat__main__name
  -#     -# = message.user.name
  -#   .chat__main__title
  -#   .chat__main__name2
  -#     %p.m-name masa
  -#     %p.date 2020/07/01
  -#   .chat__main__message
  -#     %p.message 今日は夜から雨です

  .chat__form
    = form_with model: [@group, @message], html: {class: "Form"}, local: true do |f|
      .chat__form__message
        = f.text_field :content, class: 'form__text', placeholder: 'type a message'
        = f.label :image, class: 'form__inputImage' do
          = icon('far', 'image', class: 'form__icon')
          = f.file_field :image, class: 'Hidden'
      = f.submit 'Send', class: 'Form__submit' 


-# %input.form__text{"placeholder": "type a message", "type": "text"}
-#         %label.form__inputImage
-#           = icon('far', 'image', class: 'form__icon')
-#           %input.Hidden{type: 'file'}
-#       %input.Form__submit{type: 'submit', value: 'Send'}  

app/views/messages/_message.html.haml
.MessageBox{data: {message: {id: message.id}}}
  .chat__main__name2
    %p.m-name
      = message.user.name 
    %p.date 
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .chat__main__message
    %p.message 
      = message.content
      = image_tag message.image.url, class: 'Message__image' if message.image.present?
      

app/views/messages/_side_bar.html.haml
.side-bar
  .side-bar__s-header
    .side-bar__s-header__list
      .side-bar__s-header__list__name
        = current_user.name
      .side-bar__s-header__list__icon  
        = link_to new_group_path(current_user) do
          = icon('far', 'edit', class: "list__btn--edit") 
        = link_to edit_user_path(current_user) do
          = icon('fas', 'cog', class: "list__btn--edit")

  .side-bar__navi
    - current_user.groups.each do |group|
      .side-bar__navi__group
        = link_to group_messages_path(group) do
          .side-bar__navi__group__name
            = group.name
          .side-bar__navi__group__message
            = group.show_last_message

app/views/messages/index.html.haml
= javascript_include_tag 'autoReload'
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'